name: "neptunes_pride_agent_mobile"
description: An app that combines Neptune's pride with the Neptune's Pride agent extension for mobile devices.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  event: ^3.1.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3
  http: ^1.1.0
  shared_preferences: ^2.1.2
  webview_flutter: ^4.2.2
  webview_flutter_android: ^4.10.11
  webview_flutter_wkwebview: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/npam_inject.js
    - Logo/Logo-192x192.png
    - icons/time_machine/
    - icons/ruler/
    - icons/handicap/
